[
build
]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[
deploy
]
startCommand = "hypercorn main:app --bind 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10