name: Python Application CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

# build and test
  build:

   # run on ubuntu latest
    runs-on: ubuntu-latest

    steps:

    # checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # set up python 3.11
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # run app for basic validation
    - name: Run app for basic validation
      run: |
        python app.py &
        sleep 10
        pkill -f app.py

      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }} 